### ISSUE TITLE
AttributeError: 'GopherClient' object has no attribute 'do_2'

### ISSUE THREAD

**Issue by saper** [solderpunk/VF-1#44]
I don't know what happened exactly but those two exceptions shouldn't really by reported like this:

````
VF-1> up
Welcome to the SDF Public  Access UNIX System .. est. 1987

Official Site of the Internet Gopher Club Underground Syndicate

We offer FREE and inexpensive memberships for people interested
in the UNIX system and internetworking.  Personal GOPHERSPACE
is available to all users as well as hundreds of UNIX utilities,
games and networking utilities.  We are a federally recognized
non-profit 501(c)7 organization and we are supported entirely
by donations and membership dues.  ssh://sdf.org

[1] SDF PHLOGOSPHERE (230 phlogs)/
[2] SDF GOPHERSPACE (1151 ACTIVE users)/
[3] SDF GOPHERSPACE (1369 AGED users)/
[4] SDF GOPHERSPACE (372 ANCIENT users)/
[5] SDF Frequently Asked Questions (FAQ)/
[6] SDF Accredited University Courses/
[7] Software and Documentation for various computers/
[8] GopherSpace SEARCH Engine <INP>
[9] Floodgap's GOPHERSPACE/
____________________________________________________________________________
                         Gophered by Gophernicus/97 on NetBSD/amd64 8.0_RC1
VF-1> 2
ERROR: Unknown text encoding!
If you know the correct encoding, use e.g. 'set encoding koi8-r' and
try again.  Otherwise, install the 'chardet' library for Python 3 to
enable automatic encoding detection.
VF-1> set encoding utf-8
VF-1> 2
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'GopherClient' object has no attribute 'do_2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/vf1", line 11, in <module>
    load_entry_point('VF-1==0.0.10', 'console_scripts', 'vf1')()
  File "/usr/local/lib/python3.6/site-packages/vf1.py", line 1004, in main
    gc.cmdloop()
  File "/usr/local/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.6/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/usr/local/lib/python3.6/site-packages/vf1.py", line 543, in default
    self._go_to_gi(gi)
  File "/usr/local/lib/python3.6/site-packages/vf1.py", line 284, in _go_to_gi
    f = self._decode_text(f)
  File "/usr/local/lib/python3.6/site-packages/vf1.py", line 379, in _decode_text
    raw_bytes = f.read()
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

````

**Comment by saper** [comment]
(By the way, chardet is installed):

````
> python3.6
Python 3.6.5 (default, May 10 2018, 01:13:55) 
[GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
>>> try:
...     import chardet
...     _HAS_CHARDET = True
... except ImportError:
...     _HAS_CHARDET = False
... 
>>> print(_HAS_CHARDET)
True
````

**Comment by solderpunk** [comment]
I agree that this error reporting is not good enough, and I remember occasionally seeing this kind of error (no `do_2` attribute, or similar) a few times myself.  But I haven't seen it in a long time, and I suspect this bug has been inadvertently fixed.  I'm going to close this issue for now, but anybody should feel very free to reopen it if this error appears again with the most recent version of VF-1.
