### ISSUE TITLE
Crash with g .

### ISSUE THREAD

**Issue by TheCycoONE** [solderpunk/VF-1#71]
*Environment*
MacOS 11 (Big Sur)
Python 3.9

Installed through pip3 install vf1

*Steps*
```
 ~  vf1
Welcome to VF-1!
Enjoy your flight through Gopherspace...
VF-1> g .
```

*Error*
```
ERROR: [Errno 21] Is a directory: '.'
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'GopherClient' object has no attribute 'do_g'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/vf1.py", line 237, in _go_to_gi
    f = open(gi.path, "rb")
IsADirectoryError: [Errno 21] Is a directory: '.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/vf1", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/vf1.py", line 1083, in main
    gc.cmdloop()
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/usr/local/lib/python3.9/site-packages/vf1.py", line 513, in default
    return self.onecmd(expanded)
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.9/site-packages/vf1.py", line 600, in do_go
    self._go_to_gi(gi)
  File "/usr/local/lib/python3.9/site-packages/vf1.py", line 285, in _go_to_gi
    if (isinstance(err, (ssl.SSLError)) and err.reason == "UNKNOWN_PROTOCOL") or (isinstance(err, OSError) and err.reason == "WRONG_VERSION_NUMBER"):
AttributeError: 'IsADirectoryError' object has no attribute 'reason'
```

**Comment by solderpunk** [comment]
Thanks for this bug report, and sorry for the very nearly 5 year delay in responding!

The latest release of VF-1 available via PyPi is lagging a little behind the latest code in the repository.  With the latest code, I cannot reproduce this issue.  Trying to go "up" after running "bookmarks" prints an error, but does not result in a crash.   There is no code today which tries to access a `reason` attribute.

I intend to make a new release sometime in the next two weeks (contingent on being able to recover access to my PyPi account), at which time you should be able to update and no longer experience this problem.
